apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
  labels:
    app: kibana
    component: monitoring
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    protocol: TCP
  selector:
    app: kibana
---
apiVersion: v1
kind: Service
metadata:
  name: kibana-nodeport
  namespace: monitoring
  labels:
    app: kibana
    component: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 5601
    targetPort: 5601
    nodePort: 30561
    protocol: TCP
  selector:
    app: kibana
